### ISSUE TITLE
[Feature request] Support --host flag for development server

### ISSUE THREAD

**Issue by Alex-Licea** [ManuelGil/vscode-codeigniter4-spark#1]
Hi.

All the sparks commands works great, but one that I'm still running with CLI is the local development server with --host flag. I run multiple client projects and some of them use subdomains, so the only way to support them is setting my own hosts.

It could be great if the extension can support this feature!

[CodeIgniter 4 host CLI option](https://codeigniter4.github.io/CodeIgniter4/installation/running.html#local-development-server)

**Comment by ManuelGil** [comment]
Hi Alex,

The last update of this extension was in CI 4.4. I have to update it to add some new commands from CI 4.5 version.

I am going to do some testing to see if I can add this functionality.

**Comment by ManuelGil** [comment]
Hello @Alex-Licea,

Sorry for the delay!

I recently released an update package that includes this flag. While some of the improvements do not directly affect the client side, they will contribute to more efficient code handling and facilitate future optimizations.

If you have any ideas or suggestions for new features, feel free to share them.

I'll be willing to consider new features to improve the extension.

**Comment by Alex-Licea** [comment]
Hi @ManuelGil. Thank you so much for your help and for implementing the recent update I requested! I really appreciate the improvements you’ve made; I've been using it since the release and it works great! :D

I’ll definitely keep you in mind if I come up with any ideas or suggestions for new features.

Thanks again for your support and hard work!
